# Generated by Django 3.1.5 on 2021-01-28 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='querydata',
            name='contacted_via',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='querydata',
            name='follow_up',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
