# Generated by Django 3.1.5 on 2021-01-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0002_auto_20210129_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='querydata',
            name='query',
            field=models.TextField(max_length=300),
        ),
    ]
