# Generated by Django 3.1.5 on 2021-01-29 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0004_auto_20210130_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdata',
            name='customer',
            field=models.CharField(max_length=100),
        ),
    ]
