# Generated by Django 3.1.5 on 2021-01-29 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0005_auto_20210130_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdata',
            name='query_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
