# Generated by Django 3.1.5 on 2021-01-29 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0006_customerdata_query_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerdata',
            name='query_id',
        ),
    ]
